//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QQOAuthDBModel", "FK_QzoneOAuth_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QQOauthWeb.Code.Users), "QzoneOAuth", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QQOauthWeb.Code.QzoneOAuth), true)]

#endregion

namespace QQOauthWeb.Code
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QQOAuthDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QQOAuthDBEntities object using the connection string found in the 'QQOAuthDBEntities' section of the application configuration file.
        /// </summary>
        public QQOAuthDBEntities() : base("name=QQOAuthDBEntities", "QQOAuthDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QQOAuthDBEntities object.
        /// </summary>
        public QQOAuthDBEntities(string connectionString) : base(connectionString, "QQOAuthDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QQOAuthDBEntities object.
        /// </summary>
        public QQOAuthDBEntities(EntityConnection connection) : base(connection, "QQOAuthDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QzoneOAuth> QzoneOAuth
        {
            get
            {
                if ((_QzoneOAuth == null))
                {
                    _QzoneOAuth = base.CreateObjectSet<QzoneOAuth>("QzoneOAuth");
                }
                return _QzoneOAuth;
            }
        }
        private ObjectSet<QzoneOAuth> _QzoneOAuth;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QzoneOAuth EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQzoneOAuth(QzoneOAuth qzoneOAuth)
        {
            base.AddObject("QzoneOAuth", qzoneOAuth);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QQOAuthDBModel", Name="QzoneOAuth")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QzoneOAuth : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QzoneOAuth object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="accessTokenKey">Initial value of the AccessTokenKey property.</param>
        /// <param name="accessTokenSecret">Initial value of the AccessTokenSecret property.</param>
        /// <param name="openId">Initial value of the OpenId property.</param>
        public static QzoneOAuth CreateQzoneOAuth(global::System.Int32 userId, global::System.String accessTokenKey, global::System.String accessTokenSecret, global::System.String openId)
        {
            QzoneOAuth qzoneOAuth = new QzoneOAuth();
            qzoneOAuth.UserId = userId;
            qzoneOAuth.AccessTokenKey = accessTokenKey;
            qzoneOAuth.AccessTokenSecret = accessTokenSecret;
            qzoneOAuth.OpenId = openId;
            return qzoneOAuth;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AccessTokenKey
        {
            get
            {
                return _AccessTokenKey;
            }
            set
            {
                OnAccessTokenKeyChanging(value);
                ReportPropertyChanging("AccessTokenKey");
                _AccessTokenKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AccessTokenKey");
                OnAccessTokenKeyChanged();
            }
        }
        private global::System.String _AccessTokenKey;
        partial void OnAccessTokenKeyChanging(global::System.String value);
        partial void OnAccessTokenKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AccessTokenSecret
        {
            get
            {
                return _AccessTokenSecret;
            }
            set
            {
                OnAccessTokenSecretChanging(value);
                ReportPropertyChanging("AccessTokenSecret");
                _AccessTokenSecret = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AccessTokenSecret");
                OnAccessTokenSecretChanged();
            }
        }
        private global::System.String _AccessTokenSecret;
        partial void OnAccessTokenSecretChanging(global::System.String value);
        partial void OnAccessTokenSecretChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OpenId
        {
            get
            {
                return _OpenId;
            }
            set
            {
                OnOpenIdChanging(value);
                ReportPropertyChanging("OpenId");
                _OpenId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OpenId");
                OnOpenIdChanged();
            }
        }
        private global::System.String _OpenId;
        partial void OnOpenIdChanging(global::System.String value);
        partial void OnOpenIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QQOAuthDBModel", "FK_QzoneOAuth_Users", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("QQOAuthDBModel.FK_QzoneOAuth_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("QQOAuthDBModel.FK_QzoneOAuth_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("QQOAuthDBModel.FK_QzoneOAuth_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("QQOAuthDBModel.FK_QzoneOAuth_Users", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QQOAuthDBModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static Users CreateUsers(global::System.Int32 id, global::System.String login, global::System.String password)
        {
            Users users = new Users();
            users.ID = id;
            users.Login = login;
            users.Password = password;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QQOAuthDBModel", "FK_QzoneOAuth_Users", "QzoneOAuth")]
        public QzoneOAuth QzoneOAuth
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QzoneOAuth>("QQOAuthDBModel.FK_QzoneOAuth_Users", "QzoneOAuth").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QzoneOAuth>("QQOAuthDBModel.FK_QzoneOAuth_Users", "QzoneOAuth").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QzoneOAuth> QzoneOAuthReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QzoneOAuth>("QQOAuthDBModel.FK_QzoneOAuth_Users", "QzoneOAuth");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QzoneOAuth>("QQOAuthDBModel.FK_QzoneOAuth_Users", "QzoneOAuth", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
